/**
 * GENERATED by `npm run atlas`. Do not edit by hand.
 *
 * The union below is what makes TypeScript fail the build when gameplay code
 * references a sprite that does not exist (SPEC §13.4).
 */
import type { ManualSpriteKey } from './spriteKeys.manual.ts';

/** Keys the packer found in the atlas. */
export const ATLAS_SPRITE_KEYS = [
  // (empty — no atlas packed yet)
] as const;

export type SpriteKey = ManualSpriteKey;
